name: flutter_s_umeng_push
description: 友盟推送的flutter插件，支持Android和ios
version: 0.4.0
homepage: https://github.com/jialongsu/flutter_s_umeng_push

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.um.push.flutter_s_umeng_push
        pluginClass: FlutterSUmengPushPlugin
      ios:
        pluginClass: FlutterSUmengPushPlugin
